Repository pulumi/pulumi-terraform, pull requests merged in 2019-07, with the labels that each got.

#403 Fix detailed diffs with nested computed values.
  pkg/tfbridge/diff.go
  pkg/tfbridge/diff_test.go
  pkg/tfbridge/provider.go
Labels: impact/no-changelog-required, priority/P0

#404 Update doc generation
  pkg/tfgen/docs.go
  pkg/tfgen/generate.go
  pkg/tfgen/generate_go.go
  pkg/tfgen/generate_nodejs.go
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#409 Improve TF docs generation
  pkg/tfgen/docs.go
  pkg/tfgen/generate_go.go
  pkg/tfgen/generate_nodejs.go
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#412 Lift properties so our data sources can be invoked synchronously.
  pkg/tfgen/generate_nodejs.go
Labels: impact/no-changelog-required

#415 Lift props
  pkg/tfgen/generate_nodejs.go
Labels: impact/no-changelog-required

#417 More sync investigation.
  pkg/tfgen/generate_nodejs.go
Labels: impact/no-changelog-required

#422 Allow invokes to be sync or async
  pkg/tfgen/generate_nodejs.go
Labels: impact/no-changelog-required

#425 Rename pulumi.io to pulumi.com
  README.package.md
  pkg/tfgen/generate.go
  sdk/nodejs/package.json
Labels: impact/no-changelog-required

#423 Use TF package name when emitting attribution
  pkg/tfgen/docs.go
  pkg/tfgen/generate_go.go
  pkg/tfgen/generate_nodejs.go
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#426 Use Python Codegen package from pulumi/pulumi
  go.mod
  go.sum
  pkg/tfgen/generate_python.go
  pkg/tfgen/generate_python_test.go
Labels: impact/no-changelog-required

#429 Protect against panic when RemoteState not found
  CHANGELOG.md
  pkg/provider/remote_state.go
Labels: kind/bug

#428 Protect against Provider Create panic
  CHANGELOG.md
  pkg/tfbridge/provider.go
Labels: kind/bug

#427 Treat sensitive outputs as secrets
  CHANGELOG.md
  pkg/tfbridge/provider.go
  pkg/tfbridge/schema.go
  pkg/tfbridge/schema_test.go
Labels: kind/enhancement

#414 Expanded error message about a missing field value with a config default
  CHANGELOG.md
  pkg/tfbridge/provider.go
  pkg/tfbridge/schema_test.go
Labels: kind/enhancement

#431 Enabling the ability for the Marshalling of Secrets in outputs
  pkg/tfbridge/provider.go
Labels: impact/no-changelog-required

#432 Allow a provider to specify a specific version of TypeScript
  CHANGELOG.md
  pkg/tfbridge/info.go
  pkg/tfgen/generate_nodejs.go
Labels: kind/enhancement

#434 Add support in pulumi-terraform for providing aliases for a particular resource.
  pkg/tfbridge/info.go
  pkg/tfgen/generate_nodejs.go
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#436 Include commit that was missed.
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#442 Re-enable the provider version pinning code for Python
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#435 Emit warning that pulumi binary not found when installing plugin
  CHANGELOG.md
  pkg/tfgen/generate_python.go
Labels: area/providers, kind/enhancement
