Repository pulumi/pulumi-terraform, pull requests merged in 2019-05, with the labels that each got.

#374 Add @pulumi/terraform package and state.RemoteStateReference resource
  .travis.yml
  Makefile
  cmd/pulumi-resource-terraform/main.go
  examples/.gitignore
  examples/examples_test.go
  examples/localstate/.gitignore
  examples/localstate/Pulumi.yaml
  examples/localstate/index.ts
  examples/localstate/package.json
  examples/localstate/terraform.tfstate
  examples/localstate/tsconfig.json
  go.mod
  go.sum
  pkg/provider/cty.go
  pkg/provider/cty_test.go
  pkg/provider/provider.go
  pkg/provider/remote_state.go
  pkg/provider/serve.go
  pkg/tfbridge/log.go
  pkg/version/version.go
  scripts/get-py-version
  scripts/get-py-version.go
  scripts/get-version
  scripts/publish-plugin.sh
  scripts/publish_tgz.sh
  sdk/.gitignore
  sdk/nodejs/index.ts
  sdk/nodejs/package.json
  sdk/nodejs/state/artifactoryBackendConfig.ts
  sdk/nodejs/state/azurermBackendConfig.ts
  sdk/nodejs/state/consulBackendConfig.ts
  sdk/nodejs/state/etcdBackendConfig.ts
  sdk/nodejs/state/etcdV3BackendConfig.ts
  sdk/nodejs/state/gcsBackendConfig.ts
  sdk/nodejs/state/httpBackendConfig.ts
  sdk/nodejs/state/index.ts
  sdk/nodejs/state/localBackendConfig.ts
  sdk/nodejs/state/mantaBackendConfig.ts
  sdk/nodejs/state/pgBackendConfig.ts
  sdk/nodejs/state/remoteBackendConfig.ts
  sdk/nodejs/state/remoteStateReference.ts
  sdk/nodejs/state/s3BackendConfig.ts
  sdk/nodejs/state/swiftBackendConfig.ts
  sdk/nodejs/tsconfig.json
Labels: area/providers

#377 Remove unused Makefile.pack
  Makefile.pack
Labels: impact/no-changelog-required

#378 Bridge between PEP440 and semver versions
  pkg/tfgen/generate_python.go
  pkg/tfgen/generate_python_utilities.go
Labels: impact/no-changelog-required

#381 Do not flow version information with the request
  pkg/tfgen/generate_nodejs.go
  pkg/tfgen/generate_python.go
Labels: impact/no-changelog-required

#380 Improve package README for @pulumi/terraform
  CHANGELOG.md
  Makefile
  README.package.md
Labels: area/docs
